config/routes.rb
Rails.application.routes.draw do

  get 'name/show'
  get '/ready/:id', to: 'custom#ready'
  get '/gave/:id', to: 'custom#gave'
  get 'statistics', to: 'statistics#index'
  resources :custom
  root 'custom#index'

end

app/models/custom.rb
class Custom < ActiveRecord::Base
  validates :name, presence: {message: "не может быть пустым!"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/custom_controller.rb
class CustomController < ApplicationController
  def index
    @customers = Custom.where("status > 1").order(created_at: :asc)
  end

  def new
    @customers = Custom.new
  end

  def edit
    @customers = Custom.find(params[:id])
  end

  def update
    @customers  = Custom.find(params[:id])
    if @customers.update(name: params.require(:custom).permit(:name)[:name])
      redirect_to custom_index_path, notice: 'Информация обновлена в системе!'
    else
      render action: 'edit'
    end
  end

  def create
    @customers = Custom.new(name: params.require(:custom).permit(:name)[:name], status: 3)
    if @customers.save
      redirect_to custom_index_path, notice: 'Информация добавлена в систему!'
    else
      render action: 'new'
    end
  end

  def destroy
    @customers = Custom.find(params[:id])
    @customers.update(status: 0, date_of_del: Time.now)
    redirect_to custom_index_path, notice: 'Информация удалена из системы!'
  end

  def cutom_params
    params.require(:custom).permit(:name, :status)
  end

  def ready
    @customers = Custom.find(params[:id])
    @customers.update(status: 2, date_of_ready: Time.now)
    redirect_to custom_index_path, notice: 'Данные обновленны!'
  end

  def gave
    @customers = Custom.find(params[:id])
    @customers.update(status: 1, date_of_gave: Time.now)
    redirect_to custom_index_path, notice: 'Данные обновленны!'
  end
end

app/controllers/name_controller.rb
class NameController < ApplicationController
  def show
    @custom = Custom.where("status = 3").order(created_at: :desc).take(8)
    @redy = Custom.where("status = 2").order(created_at: :asc).take(8)
  end
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    @customers = Custom.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_helper.rb
module CustomHelper
end

app/helpers/name_helper.rb
module NameHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/views/custom/create.html.erb
<h1>Custom#create</h1>
<p>Find me in app/views/custom/create.html.erb</p>

app/views/custom/destroy.html.erb
<h1>Custom#destroy</h1>
<p>Find me in app/views/custom/destroy.html.erb</p>

app/views/custom/edit.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">

      <a class="navbar-brand" href="#">FoodStory</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/custom">Список клиентов</a></li>
        <li class="active"><a href="#about">Добавить новый заказ</a></li>
        <li><a href="/statistics">Статистика</a></li>
      </ul>

    </div>
    <!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="alert alert-success" role="alert">Заполните поля для добавления абонемента.</div>
      <% if @customers.errors.any? %>
          <div id="error_explanation">

            <% @customers.errors.full_messages.each do |msg| %>
                <div class="alert alert-warning" role="alert"><%= msg %></div>
            <% end %>
          </div>
      <% end %>
      <%= form_for @customers, url: custom_index_path do |form| %>
          <%= form.text_field :name, class: "form-control", placeholder: "Имя*", maxlength: 25 %>

          <br/>
          <%= form.submit 'Добавить', class: "btn btn-primary btn-lg" %> &nbsp; <%= link_to 'Отмена',custom_index_path, class: 'btn btn-default btn-lg', role: 'button' %>
      <% end %>

    </div>
  </div>
</div>

app/views/custom/index.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">

      <a class="navbar-brand" href="#">FoodStory</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/custom">Список клиентов</a></li>
        <li><a href="/custom/new">Добавить новый заказ</a></li>
        <li><a href="/statistics">Статистика</a></li>
      </ul>

    </div>
    <!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <% if notice %>
      <br/>

      <div class="alert alert-info"> <%= notice %> </div>
  <% end %>

  <% if !@customers.blank? %>
      <table class="table table-hover cell">
        <thead>
        <tr>
          <th class="cell">Имя</th>
          <th class="cell">Статус</th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @customers.each do |custom| %>
            <tr>
              <td class="cell"><%= custom.name %></td>
              <td class="cell">
                <%= case custom.status
                when 3
                "Заказ на кухне"
                when 2
                "Заказ готов"
                when 1
                "Заказ выдан клиенту"
                else
                "Заказ удален!"
                end %>
              </td>
              <td class="cell">
                <% if custom.status == 2 %>
                    <%= link_to 'заказ забрали', "/gave/#{custom.id}", class: 'btn btn-success btn-lg', role: 'button' %>
                <% else %>
                    <%= link_to 'заказ готов', "/ready/#{custom.id}", class: 'btn btn-success btn-lg', role: 'button' %>
                <% end %>
              </td>
              <td class="cell">
                <%= button_to 'отменить заказ', custom_path(custom), class: 'btn btn-danger btn-lg', method: :delete %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
      <div class="alert alert-info"> У Вас нет заказов!.</div>
  <% end %>


  </div> <!-- /container -->

app/views/custom/new.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">

      <a class="navbar-brand" href="#">FoodStory</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/custom">Список клиентов</a></li>
        <li class="active"><a href="#about">Добавить новый заказ</a></li>
        <li><a href="/statistics">Статистика</a></li>
      </ul>

    </div>
    <!--/.nav-collapse -->
  </div>
</nav>

  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="alert alert-success" role="alert">Заполните поля для добавления абонемента.</div>
        <% if @customers.errors.any? %>
            <div id="error_explanation">

              <% @customers.errors.full_messages.each do |msg| %>
                  <div class="alert alert-warning" role="alert"><%= msg %></div>
              <% end %>
            </div>
        <% end %>
        <%= form_for @customers, url: custom_index_path do |form| %>
            <%= form.text_field :name, class: "form-control", placeholder: "Имя*", maxlength: 25 %>

            <br/>
            <%= form.submit 'Добавить', class: "btn btn-primary btn-lg" %> &nbsp; <%= link_to 'Отмена',custom_index_path, class: 'btn btn-default btn-lg', role: 'button' %>
        <% end %>

      </div>
    </div>
  </div>

app/views/custom/update.html.erb
<h1>Custom#update</h1>
<p>Find me in app/views/custom/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Для шаринга по соц сетям -->
  <meta property="og:image" content="<%= asset_path 'logo.jpg'%>" />
  <meta property="og:image:type" content="image/jpeg" />
  <meta property="og:image:width" content="196" />
  <meta property="og:image:height" content="196" />
  <title>FOOD STORY</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/name/show.html.erb
<script>
    function fresh() {
        location.reload();
    }
    setInterval("fresh()",200000);
</script>
<div class="container-fluid">
  <div class="row">
    <div class="row">
      <div class="col-md-6">
        <div class="left">
          <h3 class="text">ЗАКАЗ НА КУХНЕ</h3>
        </div>
        <% if !@custom.blank? %>
            <% @custom.each do |custom| %>
                <div class="block">
                  <%= custom.name %>
                </div>
            <% end %>
        <% end %>
      </div>

      <div class="col-md-6">
        <div class="right">
          <h3 class="text">ВАШ ЗАКАЗ ГОТОВ</h3>
        </div>
        <% if !@redy.blank? %>
            <% @redy.each do |custom| %>
                <div class="block">
                  <%= custom.name %>
                </div>
            <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/statistics/index.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">

      <a class="navbar-brand" href="#">FoodStory</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="/custom">Список клиентов</a></li>
        <li><a href="/custom/new">Добавить новый заказ</a></li>
        <li class="active"><a href="/statistics">Статистика</a></li>
      </ul>

    </div>
    <!--/.nav-collapse -->
  </div>
</nav>

<div class="container">
  <% if notice %>
      <br/>

      <div class="alert alert-info"> <%= notice %> </div>
  <% end %>

  <% if !@customers.blank? %>
      <table class="table table-hover cell">
        <thead>
        <tr>
          <th class="cell">Дата создания заказа</th>
          <th class="cell">Имя</th>
          <th class="cell">Статус</th>
          <th class="cell">Время приготовления (мин.)</th>
          <th class="cell">Время выдачи заказа (мин.)</th>
        </tr>
        </thead>
        <tbody>
        <% @customers.each do |custom| %>
            <tr>
              <td class="cell"><%= custom.created_at %></td>
              <td class="cell"><%= custom.name %></td>
              <td class="cell">
                <%= case custom.status
                      when 3
                        "Заказ на кухне"
                      when 2
                        "Заказ готов"
                      when 1
                        "Заказ выдан клиенту"
                      when 0
                        "Заказ был удален"
                      else
                        "что то пошло не так, позвоните Руслану он починит!"
                    end %>
              </td>
              <td class="cell">
                <% if custom.status == 0 %>
                    заказ был удален
                <% else %>
                    <% if !custom.date_of_ready.blank? %>
                        <%= sprintf("%.2f", (custom.date_of_ready - custom.created_at) / 60).to_f %>
                    <% else %>
                        идет расчет
                    <% end %>
                <% end %>
              </td>
              <td class="cell">
                <% if custom.status == 0 %>
                    заказ был удален
                <% else %>
                    <% if !custom.date_of_ready.blank? and !custom.date_of_gave.blank? %>
                        <%= sprintf("%.2f", (custom.date_of_gave - custom.date_of_ready) / 60).to_f %>
                    <% else %>
                        идет расчет
                    <% end %>
                <% end %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>
  <% else %>
      <div class="alert alert-info"> У Вас нет заказов!.</div>
  <% end %>


</div> <!-- /container -->